version: '2'
services:
        django:
                build: .
                command: python manage.py runserver 0.0.0.0:8000
                ports:
                        - "8000:8000"
                volumes: 
                        - .:/code
                depends_on:
                        - db                          

        db:
                image: mysql:5.7
                command: --default-authentication-plugin=mysql_native_password
                env_file:
                        - .env 
                volumes:
                        - ./mysql_data:/var/lib/mysql                         
