# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-07 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulations',
            old_name='cirfile',
            new_name='cirfile_link',
        ),
        migrations.RenameField(
            model_name='simulations',
            old_name='outfile',
            new_name='outfile_link',
        ),
    ]
